/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class SetFilePermission */

#ifndef _Included_SetFilePermission
#define _Included_SetFilePermission
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     SetFilePermission
 * Method:    cFileCall
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_SetFilePermission_cFileCall
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
