/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class JavaACL */

#ifndef _Included_JavaACL
#define _Included_JavaACL
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     JavaACL
 * Method:    javaACL
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_JavaACL_javaACL
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
