/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class PatternPrint */

#ifndef _Included_PatternPrint
#define _Included_PatternPrint
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     PatternPrint
 * Method:    pattern
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_PatternPrint_pattern
  (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
