/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class PrintSum */

#ifndef _Included_PrintSum
#define _Included_PrintSum
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     PrintSum
 * Method:    sumOfTwoNum
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_PrintSum_sumOfTwoNum
  (JNIEnv *, jobject, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
